### ISSUE TITLE
Imported history of messages is invalid

### ISSUE THREAD

**Issue by Rolling1234** [iyear/searchx#10]
The message history is imported successfully, but there is nothing in the history search, the search for the latest messages is fine. https://imgur.com/a/BLVZOer

**Comment by iyear** [comment]
Please provide the complete input command and desensitized configuration file

**Comment by Rolling1234** [comment]
> Please provide the complete input command and desensitized configuration file

https://imgur.com/a/GLSDpyp

**Comment by iyear** [comment]
@Rolling1234 Is there any log output?

**Comment by iyear** [comment]
I see this is a public channel, is it convenient to provide the channel address? I will test it locally.

**Comment by syaoranwe** [comment]
发现了同样的问题，不过我是在管理员开启了匿名的群组里出现的，发现搜索的结果中只有未开启匿名的群员的消息，缺失了【历史消息】中匿名管理员消息的索引。我将TG客户端中导出json文件里的`"from_id": "channel123456"`全部替换为`"from_id": "user1087968824"`再重新建立索引就好了。

**Comment by iyear** [comment]
@syaoranwe 感谢！将尝试修复这个bug
