### ISSUE TITLE
Request to add the function of regularly refreshing the channel history

### ISSUE THREAD

**Issue by spiritLHLS** [iyear/searchx#13]
Request to add the function of periodically refreshing the channel history, because the channel information can be modified at any time. If you only import historical information or monitor subsequent information, you cannot modify past information in bot.

**Comment by iyear** [comment]
@spiritLHLS 
https://github.com/iyear/searchx/blob/7343da804c47ce968eb81b41bf56b5e27250d68e/app/bot/handler.go#L47

Bot has done this. Both historical posts and subsequent posts will be re-indexed once the edit event is triggered.

Similarly, the same has been done for group message editing.
https://github.com/iyear/searchx/blob/7343da804c47ce968eb81b41bf56b5e27250d68e/app/bot/handler.go#L26
