### ISSUE TITLE
409报错是什么意思呢？

### ISSUE THREAD

**Issue by qwetrz007sh** [iyear/searchx#9]
请教

**Comment by iyear** [comment]
请提供日志，脱敏后的配置文件，或相关截图

**Comment by qwetrz007sh** [comment]
> 


> 请提供日志，脱敏后的配置文件，或相关截图

没想到大佬回复的这么快，正在上传图片：https://jpg.awsl.life/i/2022/07/31/z8ztfz.png

**Comment by iyear** [comment]
@qwetrz007sh 当前有多个进程跑了同一个bot，两种解决方案：
1. 找到重复的进程把他kill掉
2. 去 BotFather把token换了，用新token启动

**Comment by qwetrz007sh** [comment]
谢谢
